services:
  kocmon-booking:
    depends_on:
      postgres:
        condition: service_healthy
      #redis:
        #condition: service_healthy
    build:
      context: .
    container_name: kocmon-booking
    hostname: kocmon-booking
    environment:
      #- 'SPRING_DATASOURCE_URL=jdbc:postgresql:kocmon-postgresql:5432/kocmon-db'
      #- 'SPRING_DATASOURCE_USERNAME=localpass'
      #- 'SPRING_DATASOURCE_PASSWORD=localuser'
      - 'SPRING_PROFILES_ACTIVE=compose'
    ports:
      - "8081:8080"
    networks:
      - kocmon-net
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: 'postgres:latest'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    environment:
      - 'POSTGRES_DB=kocmon-db'
      - 'POSTGRES_USER=kocmon-db'
      - 'POSTGRES_PASSWORD=localpass'
    container_name: postgres
    hostname: kocmon-postgres
    ports:
      - '5432:5432'
    networks:
      - kocmon-net

  redis:
    image: 'redis:latest'
    restart: always
    container_name: redis
    hostname: kocmon-redis
    ports:
      - '6379:6379'
    networks:
      - kocmon-net
    volumes:
      - kocmon-redis-data:/data

volumes:
  kocmon-pg-data:
  kocmon-redis-data:

networks:
  kocmon-net:
