services:
  kocmon-booking:
    depends_on:
      postgres:
        condition: service_healthy
      #redis:
        #condition: service_healthy
    build:
      context: .
    container_name: kocmon-booking
    hostname: kocmon-booking
    environment:
      - "TODO=todo"
    ports:
      - "8081:8000"
    networks:
      - kocmon-net
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: 'postgres:latest'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10



    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    container_name: postgres
    hostname: kocmon-postgres
    ports:
      - '5432'

  redis:
    image: 'redis:latest'
    restart: always
    container_name: redis
    hostname: kocmon-redis
    ports:
      - '6379'
    volumes:
      - kocmon-redis-data:/data

volumes:
  kocmon-pg-data:
  kocmon-redis-data:

networks:
  kocmon-net:
