spring.application.name=booking
spring.datasource.url=jdbc:postgresql://kocmon-postgres:5432/kocmon-db
spring.datasource.username=kocmon-db
spring.datasource.password=localpass


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
