name: Maven package (build and test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . -t kocmon-booking:${{github.sha}}

